# 
# Makefile for PR3 crypto exercise
#
# Should contain 3 build targets
# - all: build crypto program
# - test: builds test program
# - clean: cleans directory
#
# @author: Stella Neser
# @MatNr: 1610286
#

#Compiler being used
CC=gcc



all: 
	$(CC) crypto.c -o crypto

# TODO test build target
tests:
	echo "see commit message and debug option in crypto"

clean:
	rm crypto

